drop table buildings;
drop table students;
drop table announcementSystems;

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='BUILDINGS';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='STUDENTS';
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='ANNOUNCEMENTSYSTEMS';